# -*- coding: utf-8 -*-
"""computer vision project 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186syfFYst3qDOyT1fCcPEfqq4ATG9xi2
"""

import os
import pandas as pd
from PIL import Image, ImageDraw, ImageFont
import textwrap
import random
import zipfile

# ============================================================
# SETTINGS
# ============================================================

# Google Drive mein apne paths yahan set karein
# Update: Unzip the images.zip file into a new directory first.
ZIP_IMAGE_PATH = "/content/images.zip"
IMAGE_FOLDER = "/content/images"
CSV_PATH = "/content/qoutes.csv"

# Output folder
OUTPUT_FOLDER = "/content/output"

# Final image size
IMAGE_WIDTH = 1080
IMAGE_HEIGHT = 1080

# ============================================================
# CREATE OUTPUT FOLDERS
# ============================================================

HAPPY_FOLDER = os.path.join(OUTPUT_FOLDER, "happy")
SAD_FOLDER = os.path.join(OUTPUT_FOLDER, "sad")

os.makedirs(HAPPY_FOLDER, exist_ok=True)
os.makedirs(SAD_FOLDER, exist_ok=True)

# ============================================================
# UNZIP IMAGES
# ============================================================

os.makedirs(IMAGE_FOLDER, exist_ok=True)
with zipfile.ZipFile(ZIP_IMAGE_PATH, 'r') as zip_ref:
    zip_ref.extractall(IMAGE_FOLDER)

# ============================================================
# READ CSV
# ============================================================

df = pd.read_csv(CSV_PATH)

print("CSV Columns:")
print(df.columns.tolist())

print("\nFirst few rows:")
display(df.head())

# ============================================================
# CHANGE THESE IF YOUR COLUMN NAMES ARE DIFFERENT
# ============================================================

QUOTE_COLUMN = "quotes"
LABEL_COLUMN = "sentiment"

# ============================================================
# GET HAPPY AND SAD QUOTES
# ============================================================

happy_quotes = df[
    df[LABEL_COLUMN].astype(str).str.lower().str.strip() == "happy"
][QUOTE_COLUMN].dropna().astype(str).tolist()

sad_quotes = df[
    df[LABEL_COLUMN].astype(str).str.lower().str.strip() == "sad"
][QUOTE_COLUMN].dropna().astype(str).tolist()

print("\nNumber of Happy Quotes:", len(happy_quotes))
print("Number of Sad Quotes:", len(sad_quotes))

# ============================================================
# CHECK QUOTE COUNT
# ============================================================

if len(happy_quotes) < 10:
    raise ValueError(
        f"Happy quotes sirf {len(happy_quotes)} hain. Kam az kam 10 happy quotes required hain."
    )

if len(sad_quotes) < 10:
    raise ValueError(
        f"Sad quotes sirf {len(sad_quotes)} hain. Kam az kam 10 sad quotes required hain."
    )

# Sirf 10 happy aur 10 sad quotes
happy_quotes = happy_quotes[:10]
sad_quotes = sad_quotes[:10]

# Shuffle quotes so assignment random ho
random.shuffle(happy_quotes)
random.shuffle(sad_quotes)

# ============================================================
# GET IMAGES
# ============================================================

valid_extensions = (".jpg", ".jpeg", ".png", ".webp", ".bmp", ".jfif")

# Recursively find image files within IMAGE_FOLDER and its subdirectories
image_files = []
for root, _, files in os.walk(IMAGE_FOLDER):
    for file in files:
        if file.lower().endswith(valid_extensions):
            image_files.append(os.path.join(root, file))

# Sort for consistent ordering
image_files = sorted(image_files)

print("\nNumber of images found:", len(image_files))

if len(image_files) < 10:
    raise ValueError(
        f"Folder mein sirf {len(image_files)} images mili hain. 10 images required hain."
    )

# Sirf first 10 images
image_files = image_files[:10]

# ============================================================
# FONT
# ============================================================

# Colab/Linux mein available fonts try karein
font_paths = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf", # Added a common font
    "/usr/share/fonts/truetype/msttcorefonts/Arial.ttf", # Another common font path
    "/usr/share/fonts/truetype/freefont/FreeSans.ttf" # Another common font path
]

font_path = None

for path in font_paths:
    if os.path.exists(path):
        font_path = path
        break

if font_path is None:
    # If specific paths fail, try to find any .ttf font in common system font directories
    print("Warning: Specific font paths not found. Searching for any .ttf font in common directories.")
    for root, _, files in os.walk('/usr/share/fonts'):
        for file in files:
            if file.lower().endswith('.ttf'):
                font_path = os.path.join(root, file)
                print(f"Found fallback font: {font_path}")
                break
        if font_path:
            break

if font_path is None:
    raise FileNotFoundError("Could not find any suitable font file on the system. Please ensure a .ttf font is available or upload one.")

# ============================================================
# FUNCTION: RESIZE IMAGE TO 1080x1080
# ============================================================

def resize_and_crop(image, target_width=1080, target_height=1080):

    image = image.convert("RGB")

    original_width, original_height = image.size

    target_ratio = target_width / target_height
    original_ratio = original_width / original_height

    if original_ratio > target_ratio:

        new_height = target_height
        new_width = int(new_height * original_ratio)

    else:

        new_width = target_width
        new_height = int(new_width / original_ratio)

    image = image.resize(
        (new_width, new_height),
        Image.Resampling.LANCZOS
    )

    # Center crop
    left = (new_width - target_width) // 2
    top = (new_height - target_height) // 2
    right = left + target_width
    bottom = top + target_height

    image = image.crop((left, top, right, bottom))

    return image

# ============================================================
# FUNCTION: ADD QUOTE TO IMAGE
# ============================================================

def add_quote_to_image(image, quote):
    """
    Image ke center/lower-center area mein quote add karta hai.
    """

    image = image.convert("RGBA")

    # Transparent overlay
    overlay = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)

    # Font size
    font_size = 55
    font = ImageFont.truetype(font_path, font_size)

    # Maximum text width
    max_text_width = 850

    # Word wrapping
    words = quote.split()
    lines = []
    current_line = ""

    for word in words:
        test_line = current_line + " " + word if current_line else word

        bbox = draw.textbbox(
            (0, 0),
            test_line,
            font=font
        )

        text_width = bbox[2] - bbox[0]

        if text_width <= max_text_width:
            current_line = test_line
        else:
            if current_line:
                lines.append(current_line)

            current_line = word

    if current_line:
        lines.append(current_line)

    # Line spacing
    spacing = 15

    # Calculate total text height
    line_heights = []

    for line in lines:
        bbox = draw.textbbox(
            (0, 0),
            line,
            font=font
        )

        line_height = bbox[3] - bbox[1]
        line_heights.append(line_height)

    total_text_height = sum(line_heights) + spacing * (len(lines) - 1)

    # Center text vertically
    text_y = (IMAGE_HEIGHT - total_text_height) // 2

    # Padding around text
    padding_x = 45
    padding_y = 35

    # Find maximum line width
    max_line_width = 0

    for line in lines:
        bbox = draw.textbbox(
            (0, 0),
            line,
            font=font
        )

        width = bbox[2] - bbox[0]
        max_line_width = max(max_line_width, width)

    # Background rectangle
    rect_left = (IMAGE_WIDTH - max_line_width) // 2 - padding_x
    rect_top = text_y - padding_y

    rect_right = (IMAGE_WIDTH + max_line_width) // 2 + padding_x
    rect_bottom = text_y + total_text_height + padding_y

    # Semi-transparent black background
    draw.rounded_rectangle(
        [
            rect_left,
            rect_top,
            rect_right,
            rect_bottom
        ],
        radius=30,
        fill=(0, 0, 0, 165)
    )

    # Draw each line
    current_y = text_y

    for i, line in enumerate(lines):

        bbox = draw.textbbox(
            (0, 0),
            line,
            font=font
        )

        line_width = bbox[2] - bbox[0]
        line_height = bbox[3] - bbox[1]

        text_x = (IMAGE_WIDTH - line_width) // 2

        # Slight shadow
        draw.text(
            (text_x + 3, current_y + 3),
            line,
            font=font,
            fill=(0, 0, 0, 180)
        )

        # White text
        draw.text(
            (text_x, current_y),
            line,
            font=font,
            fill=(255, 255, 255, 255)
        )

        current_y += line_height + spacing

    # Combine
    result = Image.alpha_composite(
        image,
        overlay
    )

    return result.convert("RGB")

# ============================================================
# PROCESS IMAGES
# ============================================================

used_quotes = set()

print("\nProcessing images...\n")

for i, image_path in enumerate(image_files):

    image_number = i + 1

    print(f"Processing Image {image_number}/10: {os.path.basename(image_path)}")

    # Open image
    image = Image.open(image_path)

    # Resize/crop
    image = resize_and_crop(
        image,
        IMAGE_WIDTH,
        IMAGE_HEIGHT
    )

    # --------------------------------------------------------
    # HAPPY IMAGE
# --------------------------------------------------------

    happy_quote = happy_quotes[i]

    if happy_quote in used_quotes:
        raise ValueError("Duplicate happy quote detected!")

    used_quotes.add(happy_quote)

    happy_image = add_quote_to_image(
        image.copy(),
        happy_quote
    )

    happy_output_path = os.path.join(
        HAPPY_FOLDER,
        f"happy_{image_number:02d}.jpg"
    )

    happy_image.save(
        happy_output_path,
        quality=95
    )

    # --------------------------------------------------------
    # SAD IMAGE
    # --------------------------------------------------------

    sad_quote = sad_quotes[i]

    if sad_quote in used_quotes:
        raise ValueError("Duplicate sad quote detected!")

    used_quotes.add(sad_quote)

    sad_image = add_quote_to_image(
        image.copy(),
        sad_quote
    )

    sad_output_path = os.path.join(
        SAD_FOLDER,
        f"sad_{image_number:02d}.jpg"
    )

    sad_image.save(
        sad_output_path,
        quality=95
    )

    print(f"  Happy: {happy_quote}")
    print(f"  Sad:   {sad_quote}")
    print()

# ============================================================
# VERIFY OUTPUT
# ============================================================

happy_outputs = [
    f for f in os.listdir(HAPPY_FOLDER)
    if f.lower().endswith(".jpg")
]

sad_outputs = [
    f for f in os.listdir(SAD_FOLDER)
    if f.lower().endswith(".jpg")
]

print("========================================")
print("PROCESS COMPLETED")
print("========================================")
print("Happy images:", len(happy_outputs))
print("Sad images:", len(sad_outputs))
print("Total images:", len(happy_outputs) + len(sad_outputs))
print("Unique quotes used:", len(used_quotes))
print("========================================")

# ============================================================
# CREATE ZIP FILE
# ============================================================

zip_path = "/content/quotes_images.zip"

with zipfile.ZipFile(
    zip_path,
    "w",
    zipfile.ZIP_DEFLATED
) as zipf:

    for root, dirs, files in os.walk(OUTPUT_FOLDER):

        for file in files:

            file_path = os.path.join(root, file)

            arcname = os.path.relpath(
                file_path,
                OUTPUT_FOLDER
            )

            zipf.write(
                file_path,
                arcname
            )

print("\nZIP file created:")
print(zip_path)

